
ipynb-filters: [nbprocess_filter]

project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "nbprocess"
  twitter-card: true
  reader-mode: true
  repo-branch: master
  repo-url: https://github.com/fastai/nbprocess
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        file: index.ipynb
    right:
      - icon: github
        href: https://github.com/fastai/nbprocess/
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml