ipynb-filters: [nbprocess_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "pytorch-benchmark"
  description: "Benchmarking torch xla vs distributed vs single GPU"
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: main
  repo-url: https://github.com/muellerzr/pytorch-benchmark/
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/muellerzr/pytorch-benchmark/
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
